//
// Created by Admin on 2022-11-14.
//

#ifndef COMP3940PROJECT_GAMEINSTANCESINGLETON_HPP
#define COMP3940PROJECT_GAMEINSTANCESINGLETON_HPP


class GameInstanceSingleton {

};


#endif //COMP3940PROJECT_GAMEINSTANCESINGLETON_HPP
